// Productos para el catálogo de videojuegos
const products = [
  {
    id: 1,
    name: 'Figura Master Chief – Halo Infinite',
    image: 'https://m.media-amazon.com/images/I/71ugrrkR3jS._UF350,350_QL50_.jpg',
    description: 'Figura de acción articulada de Master Chief con rifle de combate, inspirada en Halo Infinite.',
    price: 44.99,
    category: 'Figuras Coleccionables',
  },
  {
    id: 2,
    name: 'Nintendo Switch 2',
    image: 'https://multimedia.bbycastatic.ca/multimedia/products/500x500/192/19296/19296507.jpg',
    description: 'Consola híbrida de nueva generación de Nintendo con pantalla mejorada y rendimiento optimizado para juegos en modo portátil y dock.',
    price: 549.99,
    category: 'Consolas',
  },
  {
    id: 3,
    name: 'Figura Link – Zelda: Tears of the Kingdom',
    image: 'https://www.ociostock.com/productos/imagenes/img_344695_1263a772006568ea99d7ef337fd93649_20.jpg',
    description: 'Figura de colección de Link con su atuendo de Tears of the Kingdom y espada maestra.',
    price: 54.99,
    category: 'Figuras Coleccionables',
  },
  {
    id: 4,
    name: 'PlayStation 5',
    image: 'https://cdn.grupoelcorteingles.es/SGFM/dctm/MEDIA03/202407/11/00194481001025____9__1200x1200.jpg?impolicy=Resize&width=1200&height=1200',
    description: 'Consola de última generación de Sony con gráficos 4K y SSD ultrarrápido.',
    price: 649.99,
    category: 'Consolas',
  },
  {
    id: 5,
    name: 'DualSense Wireless Controller',
    image: 'https://ecsonyb2c.vtexassets.com/arquivos/ids/244234-800-800?v=637365582088830000&width=800&height=800&aspect=true',
    description: 'Control inalámbrico de PS5 con gatillos adaptativos y respuesta háptica avanzada.',
    price: 79.99,
    category: 'Accesorios',
  },
  {
    id: 6,
    name: 'Figura Kratos – God of War',
    image: 'https://ciudadmangacr.com/cdn/shop/files/36.500-4580416947336_1_0fa81773-088f-4d33-bfb4-1643f73877fb.jpg?v=1734645636',
    description: 'Figura coleccionable detallada de Kratos, protagonista de God of War Ragnarök para PlayStation 5.',
    price: 49.99,
    category: 'Figuras Coleccionables',
  },
  {
    id: 7,
    name: 'The Legend of Zelda: Tears of the Kingdom',
    image: 'https://assets.nintendo.com/image/upload/c_fill,w_1200/q_auto:best/f_auto/dpr_2.0/ncom/My%20Nintendo%20Store/EN-US/Nintendo%20Switch%202/Software/The%20Legend%20of%20Zelda%20Tears%20of%20the%20Kingdom%20%E2%80%93%20Nintendo%20Switch%202%20Edition/121504-nintendo-switch-2-the-legend-of-zelda-tears-of-the-kingdom-nintendo-switch-2-edition-2000x2000',
    description: 'Aventura épica de mundo abierto para Nintendo Switch, secuela directa de Breath of the Wild.',
    price: 69.99,
    category: 'Juegos',
  },
  {
    id: 8,
    name: 'Figura Banjo y Kazooie',
    image: 'https://f.fcdn.app/imgs/a9ff9e/tienda.soysantander.com.uy/comp/4a5b/original/catalogo/20-045496893750-P_20-045496893750_1/1920-1200/amiibo-banjo-and-kazooie-figura.jpg',
    description: 'Colorida figura de Banjo y Kazooie, un clásico de Rare para fans de Xbox y Nintendo.',
    price: 42.99,
    category: 'Figuras Coleccionables',
  },
  {
    id: 9,
    name: 'Nintendo Pro Controller',
    image: 'https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_1.5/ncom/My%20Nintendo%20Store/EN-US/Nintendo%20Switch%202/Controllers/Pro%20Controllers/123674-nintendo-switch-2-pro-controller-front-2000x2000',
    description: 'Control ergonómico de Nintendo con excelente autonomía y compatibilidad total con Switch.',
    price: 69.99,
    category: 'Accesorios',
  },
  {
    id: 10,
    name: 'Mario Kart World',
    image: 'https://sniper.cl/cdn/shop/files/mariokartworldnsw2.webp?v=1746163281',
    description: 'Nueva entrega de la saga Mario Kart con circuitos globales y modos online mejorados para Nintendo Switch.',
    price: 69.99,
    category: 'Juegos',
  },
  {
    id: 11,
    name: 'God of War: Ragnarök',
    image: 'https://www.artefacta.com/media/catalog/product/1/3/137675.png?optimize=medium&bg-color=255,255,255&fit=bounds&height=1040&width=1040&canvas=1040:1040&format=jpeg',
    description: 'Épico juego de acción y aventura exclusivo de PlayStation con narrativa cinematográfica.',
    price: 69.99,
    category: 'Juegos',
  },
  {
    id: 12,
    name: 'Figura Mario – Mario Kart World',
    image: 'https://media.game.es/COVERV2/3D_L/214/214373.png',
    description: 'Figura de Mario con su kart clásico basada en la nueva entrega Mario Kart World.',
    price: 39.99,
    category: 'Figuras Coleccionables',
  },
  {
    id: 13,
    name: 'Xbox Series X',
    image: 'https://xdvideogames.com/wp-content/uploads/2024/11/20015278_ALT09.jpeg',
    description: 'Potente consola de Microsoft con soporte para juegos 4K y almacenamiento SSD de alta velocidad.',
    price: 579.99,
    category: 'Consolas',
  },
  {
    id: 14,
    name: 'Xbox Wireless Headset',
    image: 'https://m.media-amazon.com/images/I/41SujWSlGSL.jpg',
    description: 'Auriculares inalámbricos de Xbox con sonido espacial y micrófono con cancelación de ruido.',
    price: 99.99,
    category: 'Accesorios',
  },
  {
    id: 15,
    name: 'Figura Aloy – Horizon Forbidden West',
    image: 'https://sw6.elbenwald.de/media/f4/75/9e/1673653332/E1073520_1.jpg',
    description: 'Impresionante figura de Aloy con arco y detalles realistas, inspirada en Horizon Forbidden West.',
    price: 59.99,
    category: 'Figuras Coleccionables',
  },
  {
  id: 16,
  name: 'Auriculares Pulse 3D – PS5',
  image: 'https://ecsonyb2c.vtexassets.com/arquivos/ids/244228/PS5_WHS_Pshot_A.jpg?v=637365513470200000',
  description: 'Auriculares inalámbricos optimizados para audio 3D en PlayStation 5, con doble micrófono y batería de larga duración.',
  price: 99.99,
  category: 'Accesorios',
},
{
  id: 17,
  name: 'Xbox Series S',
  image: 'https://www.artefacta.com/media/catalog/product/1/4/142319.jpg.jpg?optimize=medium&bg-color=255,255,255&fit=bounds&height=1040&width=1040&canvas=1040:1040',
  description: 'Consola compacta y digital de Microsoft, ideal para juegos en resolución 1440p y almacenamiento SSD rápido.',
  price: 299.99,
  category: 'Consolas',
},
{
  id: 18,
  name: 'Spider-Man 2',
  image: 'https://i.ebayimg.com/images/g/6hkAAOSw9pZoLwHl/s-l500.jpg',
  description: 'Juego exclusivo de PS5 con gráficos espectaculares y mecánicas mejoradas del hombre araña.',
  price: 69.99,
  category: 'Juegos',
},
{
  id: 19,
  name: 'Nintendo Switch Lite',
  image: 'https://elbarbaro.ec/wp-content/uploads/2022/06/swith-lite-900x900-1.jpg',
  description: 'Versión compacta de la consola Nintendo Switch, diseñada para jugar únicamente en modo portátil.',
  price: 219.99,
  category: 'Consolas',
},
{
  id: 20,
  name: 'Teclado Razer Tartarus V2',
  image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTR_KC6TejLZiAlrOQ2fmFCwF_VxOJX_j86GA&s',
  description: 'Teclado ergonómico para juegos con teclas programables y retroiluminación RGB, compatible con consolas y PC.',
  price: 89.99,
  category: 'Accesorios',
},
{
  id: 21,
  name: 'Forza Horizon 5',
  image: 'https://i.ebayimg.com/images/g/MLEAAOSw-bhhzquI/s-l640.jpg',
  description: 'Simulador de carreras de mundo abierto para Xbox, con escenarios mexicanos y cientos de vehículos disponibles.',
  price: 59.99,
  category: 'Juegos',
},
{
  id: 22,
  name: 'Steam Deck',
  image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQToIHX4TvciPWhFo3ZtymYwOrBz5HEozmFaQ&s',
  description: 'Consola portátil de Valve con sistema SteamOS y compatibilidad con miles de juegos de PC.',
  price: 399.99,
  category: 'Consolas',
},
{
  id: 23,
  name: 'Hori Split Pad Pro',
  image: 'https://http2.mlstatic.com/D_NQ_NP_947200-MEC75977010310_052024-O.webp',
  description: 'Mandos laterales ergonómicos para Nintendo Switch, ideales para sesiones largas en modo portátil.',
  price: 49.99,
  category: 'Accesorios',
},
{
  id: 24,
  name: 'Starfield',
  image: 'https://bjs.scene7.com/is/image/bjs/316831?$bjs-Initial600$',
  description: 'Ambicioso juego de exploración espacial de Bethesda, exclusivo para Xbox Series X|S y PC.',
  price: 69.99,
  category: 'Juegos',
}

];

export default products;
